name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Koristi stabilnu verziju

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Check Node.js and NPM version
      run: |
        node -v
        npm -v

    - name: Install correct Chart.js version
      run: npm install chart.js@3.9.1

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build project
      run: npm run build --if-present
      
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/  # Ovo je folder gde Vue pravi build fajlove
        server-dir: /public_html/smartera.razmenidom.com/  # Postavi gde treba fajlovi da idu na hostingu
